#!/usr/bin/env python3
"""Generate Not-Happy-Jan call-centre SFX with Stable Audio Open 1.0.

Provenance record (issue #52): every phone/handset/ring/glitch sound effect in the
media bundle is generated by this script from the prompts below, using
`stabilityai/stable-audio-open-1.0` (Stability AI Community License — outputs owned
by the user, released CC0). No third-party sample-bank audio is used.

Each category produces N raw variations plus a telephone-band-filtered version, so a
human can audition and approve per clip. Run on a CUDA box (built for an RTX 5090):

    HF_TOKEN=… ~/sao-gen/.venv/bin/python generate-sfx.py --out ~/sao-gen/out
"""
from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import soundfile as sf
import torch
from diffusers import StableAudioPipeline
from scipy.signal import butter, sosfilt

MODEL = "stabilityai/stable-audio-open-1.0"
SR = 44100
NEGATIVE = "music, song, melody, speech, talking, voice, vocals, reverb, low quality"

# (key, prompt, seconds, n_variations)
CATEGORIES = [
    ("handset_pickup",  "telephone handset lifted off the cradle, single plastic receiver pickup click, dry close mic, no music", 1.0, 12),
    ("handset_hangup",  "telephone receiver hung up on the cradle, plastic hang-up clunk, dry close mic, no music", 1.0, 12),
    ("handset_handling","handling a desk telephone receiver, plastic creak and coiled cord rustle, fumbling the handset, dry close mic", 1.5, 12),
    ("button_press",    "single telephone keypad button press, short soft plastic click, dry, no music", 0.6, 10),
    ("dial_tones",      "telephone touch-tone DTMF dialing tones, dialing a phone number, electronic beeps", 1.8, 10),
    ("desk_ring",       "old desk telephone ringing, electromechanical bell ring burst, analogue phone ringtone", 2.5, 12),
    ("busy_tone",       "telephone busy signal, repeating busy tone, engaged line beep", 1.5, 8),
    ("line_glitch",     "telephone line digital glitch, brief electronic crackle and error blip, data corruption stutter, dry", 1.0, 12),
    ("line_static",     "telephone line static hiss and electrical interference, short noisy burst, crosstalk", 1.2, 10),
    ("transfer_blip",   "call transfer beep, phone system transition blip, electronic switch tone", 0.8, 10),
    ("error_buzz",      "harsh rejected-call error buzzer, short angry tone, dead line buzz", 1.0, 10),
]


def phone_filter(x: np.ndarray, sr: int = SR) -> np.ndarray:
    """Telephone band-pass (~300-3400 Hz) + mild compression for the call-centre feel."""
    sos = butter(4, [300, 3400], btype="band", fs=sr, output="sos")
    y = sosfilt(sos, x)
    peak = np.max(np.abs(y)) or 1.0
    y = y / peak
    y = np.tanh(y * 1.8) * 0.9            # soft saturate/compress
    return y.astype(np.float32)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=Path.home() / "sao-gen" / "out")
    ap.add_argument("--steps", type=int, default=120)
    ap.add_argument("--seed", type=int, default=20260609)
    args = ap.parse_args()

    device = "cuda" if torch.cuda.is_available() else "cpu"
    dtype = torch.float16 if device == "cuda" else torch.float32
    print(f"loading {MODEL} on {device}/{dtype} …")
    pipe = StableAudioPipeline.from_pretrained(MODEL, torch_dtype=dtype).to(device)

    args.out.mkdir(parents=True, exist_ok=True)
    manifest = []
    for key, prompt, secs, n in CATEGORIES:
        cdir = args.out / key
        cdir.mkdir(parents=True, exist_ok=True)
        print(f"\n[{key}] {n}× {secs}s — {prompt!r}")
        # Generate in small sub-batches: the oobleck VAE decode is memory-heavy at
        # 44.1 kHz, so decoding a big batch at once OOMs even a 32 GB card.
        CHUNK = 3
        base_seed = args.seed + (abs(hash(key)) % 100000)
        result = []
        chunk = 0
        while len(result) < n:
            k = min(CHUNK, n - len(result))
            gen = torch.Generator(device).manual_seed(base_seed + chunk * 7919)
            audios = pipe(
                prompt=prompt,
                negative_prompt=NEGATIVE,
                num_inference_steps=args.steps,
                audio_end_in_s=float(secs),
                num_waveforms_per_prompt=k,
                generator=gen,
            ).audios  # (k, channels, samples)
            result.extend(audios)
            chunk += 1
            if device == "cuda":
                torch.cuda.empty_cache()
        for i, wav in enumerate(result):
            audio = wav.T.float().cpu().numpy()      # (samples, channels)
            mono = audio.mean(axis=1)
            mono = mono / (np.max(np.abs(mono)) or 1.0)
            raw_p = cdir / f"{key}_{i:02d}_raw.wav"
            tel_p = cdir / f"{key}_{i:02d}_phone.wav"
            sf.write(raw_p, mono, SR)
            sf.write(tel_p, phone_filter(mono), SR)
            manifest.append(f"{key}/{raw_p.name}\t{key}/{tel_p.name}\t{prompt}")
        print(f"  wrote {n} raw + {n} phone clips → {cdir}")

    (args.out / "MANIFEST.tsv").write_text(
        "raw\tphone\tprompt\n" + "\n".join(manifest) + "\n"
    )
    print(f"\nDone. {len(manifest)} variations under {args.out}")


if __name__ == "__main__":
    main()
